export const STORAGE_KEY = "next-bite-mvp";
export const mealNames = ["Breakfast", "Lunch", "Dinner", "Snacks / Drinks"];
export const preferenceTags = [
    "Chinese-style",
    "Taiwanese-style",
    "Japanese",
    "Korean",
    "American light meals",
    "Bowl meals",
    "Set meals",
    "Wraps / sandwiches",
    "Portable meals",
    "Soupy meals",
    "Rice-based meals",
    "Noodle-based meals",
    "High-protein",
    "Light meals",
    "Warm meals",
    "Comfort meals",
    "Quick grocery meals",
    "Takeout-friendly",
    "Vegetable-forward",
    "Breakfast-for-dinner",
    "Plant-protein",
    "Mediterranean",
    "Mexican-inspired",
];
export const avoidTags = [
    "Fried food",
    "Dairy",
    "Beef",
    "Pork",
    "Lamb",
    "Organ meats",
    "Cilantro",
    "Celery",
    "Bitter melon",
    "Eggplant",
    "Okra",
    "Green bell pepper",
    "Spicy food",
    "Shellfish",
    "Fishy seafood",
    "Raw food",
    "Cold food",
    "Sweet drinks",
    "Processed food",
    "Large portions",
    "Late-night heavy meals",
    "Egg",
];
export const mealOptions = {
    protein: [
        "Chicken",
        "Turkey",
        "Chicken sausage",
        "Beef",
        "Pork",
        "Ham",
        "Bacon",
        "Fish",
        "Salmon",
        "Tuna",
        "Cod",
        "Shrimp",
        "Crab",
        "Tofu",
        "Tempeh",
        "Egg",
        "Greek yogurt",
        "Cottage cheese",
        "Beans",
        "Black beans",
        "Chickpeas",
        "Edamame",
    ],
    vegetables: [
        "Leafy greens",
        "Spinach",
        "Romaine",
        "Kale",
        "Broccoli",
        "Cauliflower",
        "Brussels sprouts",
        "Cabbage",
        "Napa cabbage",
        "Bok choy",
        "Mushrooms",
        "Tomato",
        "Cucumber",
        "Carrot",
        "Bell pepper",
        "Zucchini",
        "Asparagus",
        "Green beans",
        "Snap peas",
        "Corn",
        "Onion",
        "Sweet onion",
        "Celery",
        "Avocado",
        "Mixed vegetables",
        "Seaweed",
    ],
    carbs: [
        "Rice",
        "Brown rice",
        "Jasmine rice",
        "Rice noodles",
        "Noodles",
        "Pasta",
        "Bread",
        "Bagel",
        "Wrap",
        "Tortilla",
        "Oatmeal",
        "Granola",
        "Cereal",
        "Sweet potato",
        "Potato",
        "Mashed potato",
        "Quinoa",
        "Farro",
        "Couscous",
        "Crackers",
        "Toast",
        "Congee",
        "Bao / bun",
    ],
    fruit: ["Berries", "Strawberries", "Blueberries", "Banana", "Apple", "Orange", "Mandarin", "Grapes", "Watermelon", "Cantaloupe", "Pineapple", "Mango", "Kiwi", "Peach", "Pear", "Plum", "Cherries", "Avocado", "Grapefruit"],
    soup: ["Miso soup", "Tomato soup", "Seaweed soup", "Bone broth", "Vegetable soup", "Chicken soup", "Tofu soup", "Corn soup", "Hot and sour soup", "Clam soup"],
    drink: [
        "Water",
        "Sparkling water",
        "Tea",
        "Green tea",
        "Black tea",
        "Coffee",
        "Iced coffee",
        "Milk",
        "Soy milk",
        "Oat milk",
        "Almond milk",
        "Yogurt drink",
        "Protein shake",
        "Smoothie",
        "Green juice",
        "Orange juice",
        "Apple juice",
        "Coconut water",
        "Soda",
        "Diet soda",
        "Sweet drink",
        "Sports drink",
        "Energy drink",
        "Milk tea",
        "Boba",
        "Beer",
        "Wine",
        "Cocktail",
        "Alcohol",
    ],
    cookingMethod: ["Stir-fried", "Grilled", "Steamed", "Boiled", "Fried", "Soup / stew", "Raw / cold", "Other"],
    mealSource: ["Home-cooked", "Takeout", "Restaurant", "Ready-made"],
    portion: ["Small", "Medium", "Large"],
};
const uniqueOptions = (groups) => [...new Set(groups.flatMap((group) => group.options))];
export const sectionDescriptions = {
    Breakfast: "A simple start is enough. Just capture the basics.",
    Lunch: "Think of the meal you actually had, not the ideal one.",
    Dinner: "This helps shape the next recommendation the most.",
    "Snacks / Drinks": "Include fruit, drinks, or small bites that changed the feel of the day.",
};
export const categoryLabels = {
    protein: "Protein",
    vegetables: "Vegetables",
    carbs: "Carbs",
    fruit: "Fruit",
    soup: "Soup",
    drink: "Drink",
};
export const mealOptionGroups = {
    protein: [
        { label: "Poultry", options: ["Chicken", "Turkey", "Chicken sausage"] },
        { label: "Red meat", options: ["Beef", "Pork", "Ham", "Bacon"] },
        { label: "Seafood", options: ["Fish", "Salmon", "Tuna", "Cod", "Shrimp", "Crab"] },
        { label: "Plant-based", options: ["Tofu", "Tempeh", "Beans", "Black beans", "Chickpeas", "Edamame"] },
        { label: "Other protein", options: ["Egg", "Greek yogurt", "Cottage cheese"] },
    ],
    vegetables: [
        { label: "Leafy greens", options: ["Leafy greens", "Spinach", "Romaine", "Kale"] },
        { label: "Asian-friendly staples", options: ["Napa cabbage", "Bok choy", "Cabbage", "Seaweed", "Mushrooms"] },
        { label: "Cruciferous", options: ["Broccoli", "Cauliflower", "Brussels sprouts"] },
        { label: "Fresh produce", options: ["Tomato", "Cucumber", "Carrot", "Bell pepper", "Zucchini", "Asparagus"] },
        { label: "Everyday sides", options: ["Green beans", "Snap peas", "Corn", "Onion", "Sweet onion", "Celery", "Avocado", "Mixed vegetables"] },
    ],
    carbs: [
        { label: "Rice and grains", options: ["Rice", "Brown rice", "Jasmine rice", "Quinoa", "Farro", "Couscous"] },
        { label: "Noodles and pasta", options: ["Rice noodles", "Noodles", "Pasta"] },
        { label: "Bread and wraps", options: ["Bread", "Bagel", "Wrap", "Tortilla", "Toast", "Crackers", "Bao / bun"] },
        { label: "Breakfast carbs", options: ["Oatmeal", "Granola", "Cereal"] },
        { label: "Starchy sides", options: ["Sweet potato", "Potato", "Mashed potato", "Congee"] },
    ],
    fruit: [
        { label: "Berries", options: ["Berries", "Strawberries", "Blueberries"] },
        { label: "Daily basics", options: ["Banana", "Apple", "Pear", "Grapes"] },
        { label: "Citrus", options: ["Orange", "Mandarin", "Grapefruit"] },
        { label: "Melons and tropical", options: ["Watermelon", "Cantaloupe", "Pineapple", "Mango", "Kiwi"] },
        { label: "Stone fruit", options: ["Peach", "Plum", "Cherries", "Avocado"] },
    ],
    soup: [
        { label: "Light soups", options: ["Miso soup", "Seaweed soup", "Vegetable soup", "Corn soup"] },
        { label: "Heartier soups", options: ["Tomato soup", "Bone broth", "Chicken soup", "Tofu soup", "Hot and sour soup", "Clam soup"] },
    ],
    drink: [
        { label: "Water and tea", options: ["Water", "Sparkling water", "Tea", "Green tea", "Black tea"] },
        { label: "Coffee", options: ["Coffee", "Iced coffee"] },
        { label: "Milk and dairy-style", options: ["Milk", "Soy milk", "Oat milk", "Almond milk", "Yogurt drink"] },
        { label: "Juices and smoothies", options: ["Smoothie", "Green juice", "Orange juice", "Apple juice", "Coconut water", "Protein shake"] },
        { label: "Sweet drinks", options: ["Sweet drink", "Milk tea", "Boba", "Soda", "Diet soda", "Sports drink", "Energy drink"] },
        { label: "Alcohol", options: ["Beer", "Wine", "Cocktail", "Alcohol"] },
    ],
};
export const snackOptionGroups = {
    protein: [
        { label: "Protein snacks", options: ["Greek yogurt", "Yogurt drink", "Protein shake", "Jerky", "String cheese", "Cottage cheese"] },
        { label: "Plant-based protein", options: ["Edamame", "Roasted chickpeas", "Trail mix", "Nuts", "Nut butter"] },
    ],
    vegetables: [
        { label: "Fresh crunchy", options: ["Baby carrots", "Mini cucumbers", "Celery sticks", "Cherry tomatoes", "Snap peas"] },
        { label: "Light prepared", options: ["Veggie tray", "Seaweed snacks", "Pickles"] },
    ],
    carbs: [
        { label: "Packaged snacks", options: ["Crackers", "Pretzels", "Popcorn", "Granola bar", "Protein bar", "Rice cakes"] },
        {
            label: "Sweet snacks",
            options: [
                "Cookies",
                "Cookie sandwich",
                "Chocolate",
                "Muffin",
                "Pastry",
                "Cake",
                "Cupcake",
                "Brownie",
                "Donut",
                "Cheesecake",
                "Ice cream",
                "Ice cream bar",
                "Frozen yogurt",
                "Pudding",
            ],
        },
        { label: "Chips and crunchy", options: ["Potato chips", "Tortilla chips", "Pita chips"] },
    ],
    fruit: [
        { label: "Whole fruit", options: ["Banana", "Apple", "Orange", "Mandarin", "Grapes"] },
        { label: "Berry and cut fruit", options: ["Strawberries", "Blueberries", "Watermelon", "Pineapple", "Fruit cup"] },
    ],
    soup: [
        { label: "Quick warm snacks", options: ["Cup soup", "Instant miso soup", "Tomato soup"] },
    ],
    drink: [
        { label: "Everyday drinks", options: ["Water", "Sparkling water", "Tea", "Coffee", "Milk"] },
        { label: "Grocery drinks", options: ["Yogurt drink", "Smoothie", "Orange juice", "Apple juice", "Coconut water"] },
        { label: "Sweet or fun drinks", options: ["Milk tea", "Boba", "Soda", "Energy drink"] },
    ],
};
export const snackMealOptions = {
    protein: uniqueOptions(snackOptionGroups.protein),
    vegetables: uniqueOptions(snackOptionGroups.vegetables),
    carbs: uniqueOptions(snackOptionGroups.carbs),
    fruit: uniqueOptions(snackOptionGroups.fruit),
    soup: uniqueOptions(snackOptionGroups.soup),
    drink: uniqueOptions(snackOptionGroups.drink),
};
export const createEmptyMeal = () => ({
    protein: [],
    vegetables: [],
    carbs: [],
    fruit: [],
    soup: [],
    drink: [],
    cookingMethod: "Boiled",
    mealSource: "Home-cooked",
    portion: "Medium",
});
export const seedProfile = {
    heightCm: "165",
    heightFt: "5",
    heightIn: "5",
    weightKg: "60",
    weightLb: "132",
    heightUnit: "cm",
    weightUnit: "kg",
    feelToday: "Normal",
    activityLevel: "Moderate",
    eatingStyle: "Both",
    preferenceTags: ["Chinese-style", "Japanese", "Soupy meals", "Light meals"],
    avoidTags: ["Dairy"],
};
export const seedTodayLog = {
    Breakfast: { ...createEmptyMeal(), protein: ["Egg"], carbs: ["Oatmeal"], fruit: ["Banana"], drink: ["Coffee"], portion: "Small" },
    Lunch: { ...createEmptyMeal(), protein: ["Chicken"], vegetables: ["Broccoli", "Mixed vegetables"], carbs: ["Rice"], drink: ["Tea"], cookingMethod: "Stir-fried", mealSource: "Takeout" },
    Dinner: createEmptyMeal(),
    "Snacks / Drinks": { ...createEmptyMeal(), fruit: ["Apple"], drink: ["Water"], cookingMethod: "Raw / cold", mealSource: "Ready-made", portion: "Small" },
};
const historyMeals = [
    [
        { protein: ["Egg"], carbs: ["Bread"], drink: ["Coffee"], portion: "Small" },
        { protein: ["Pork"], vegetables: ["Leafy greens"], carbs: ["Rice"], cookingMethod: "Stir-fried", mealSource: "Takeout" },
        { protein: ["Fish"], vegetables: ["Seaweed", "Mushrooms"], carbs: ["Rice"], soup: ["Miso soup"], cookingMethod: "Soup / stew" },
        { fruit: ["Orange"], drink: ["Tea"], portion: "Small", cookingMethod: "Raw / cold" },
    ],
    [
        { protein: ["Tofu"], carbs: ["Oatmeal"], drink: ["Soy milk"], portion: "Small" },
        { protein: ["Chicken"], vegetables: ["Tomato"], carbs: ["Tortilla"], cookingMethod: "Grilled", mealSource: "Restaurant" },
        { protein: ["Shrimp"], vegetables: ["Mixed vegetables"], carbs: ["Noodles"], cookingMethod: "Fried", mealSource: "Takeout" },
        { fruit: ["Cantaloupe"], drink: ["Water"], portion: "Small", cookingMethod: "Raw / cold" },
    ],
    [
        { protein: ["Egg"], carbs: ["Bread"], fruit: ["Apple"] },
        { protein: ["Beef"], vegetables: ["Broccoli"], carbs: ["Rice"], cookingMethod: "Stir-fried", mealSource: "Takeout" },
        { protein: ["Tofu"], vegetables: ["Leafy greens", "Mushrooms"], carbs: ["Rice"], soup: ["Vegetable soup"], cookingMethod: "Soup / stew" },
        { drink: ["Sparkling water"], portion: "Small", cookingMethod: "Raw / cold" },
    ],
    [
        { protein: ["Egg"], carbs: ["Oatmeal"], fruit: ["Berries"] },
        { protein: ["Chicken"], vegetables: ["Mixed vegetables"], carbs: ["Rice"], cookingMethod: "Grilled", mealSource: "Takeout" },
        { protein: ["Fish"], vegetables: ["Seaweed"], carbs: ["Sweet potato"], soup: ["Miso soup"], cookingMethod: "Steamed" },
        { drink: ["Tea"], portion: "Small", cookingMethod: "Raw / cold" },
    ],
    [
        { carbs: ["Bread"], drink: ["Coffee"], portion: "Small" },
        { protein: ["Pork"], vegetables: ["Leafy greens"], carbs: ["Noodles"], cookingMethod: "Fried", mealSource: "Restaurant" },
        { protein: ["Tofu"], vegetables: ["Tomato"], carbs: ["Rice"], soup: ["Tomato soup"], cookingMethod: "Soup / stew" },
        { fruit: ["Banana"], drink: ["Water"], portion: "Small", cookingMethod: "Raw / cold" },
    ],
    [
        { protein: ["Egg"], carbs: ["Bread"], drink: ["Soy milk"], portion: "Small" },
        { protein: ["Fish"], vegetables: ["Broccoli"], carbs: ["Rice"], cookingMethod: "Steamed", mealSource: "Restaurant" },
        { protein: ["Chicken"], vegetables: ["Mixed vegetables"], carbs: ["Tortilla"], cookingMethod: "Grilled", mealSource: "Takeout" },
        { fruit: ["Orange"], drink: ["Tea"], portion: "Small", cookingMethod: "Raw / cold" },
    ],
];
const buildSeedLogs = () => historyMeals
    .map((dayMeals) => ({
    Breakfast: { ...createEmptyMeal(), ...dayMeals[0] },
    Lunch: { ...createEmptyMeal(), ...dayMeals[1] },
    Dinner: { ...createEmptyMeal(), ...dayMeals[2] },
    "Snacks / Drinks": { ...createEmptyMeal(), ...dayMeals[3] },
}))
    .concat([seedTodayLog]);
export const cloneMealEntry = (meal) => ({
    protein: [...meal.protein],
    vegetables: [...meal.vegetables],
    carbs: [...meal.carbs],
    fruit: [...meal.fruit],
    soup: [...meal.soup],
    drink: [...meal.drink],
    cookingMethod: meal.cookingMethod,
    mealSource: meal.mealSource,
    portion: meal.portion,
});
export const cloneTodayLog = (todayLog) => Object.fromEntries(mealNames.map((mealName) => [mealName, cloneMealEntry(todayLog[mealName])]));
const toIsoDate = (date) => date.toISOString().slice(0, 10);
const buildSevenDaySeeds = () => {
    const formatter = new Intl.DateTimeFormat("en-US", { weekday: "short" });
    const today = new Date();
    today.setHours(12, 0, 0, 0);
    const logs = buildSeedLogs();
    return logs.map((todayLog, index) => {
        const offset = logs.length - 1 - index;
        const date = new Date(today);
        date.setDate(today.getDate() - offset);
        const isToday = offset === 0;
        const label = isToday ? "Today" : offset === 1 ? "Yesterday" : formatter.format(date);
        return {
            id: toIsoDate(date),
            date: toIsoDate(date),
            label,
            isToday,
            todayLog: cloneTodayLog(todayLog),
        };
    });
};
export const seedHistory = buildSevenDaySeeds();
export const cloneProfile = (profile) => ({
    ...profile,
    preferenceTags: [...profile.preferenceTags],
    avoidTags: [...profile.avoidTags],
});
export const cloneDay = (day) => ({
    ...day,
    todayLog: cloneTodayLog(day.todayLog),
});
export const createSeededState = () => ({
    profile: cloneProfile(seedProfile),
    days: seedHistory.map(cloneDay),
    selectedDayId: seedHistory[seedHistory.length - 1]?.id ?? "",
});
export const createBlankState = () => ({
    profile: {
        ...cloneProfile(seedProfile),
        preferenceTags: [],
        avoidTags: [],
    },
    days: seedHistory.map((day) => ({
        ...day,
        todayLog: Object.fromEntries(mealNames.map((mealName) => [mealName, createEmptyMeal()])),
    })),
    selectedDayId: seedHistory[seedHistory.length - 1]?.id ?? "",
});
export const recommendationDataset = [
    {
        id: "salmon-rice-bowl-veg",
        title: "Salmon Rice Bowl with Vegetables",
        tags: ["rice-based", "japanese-inspired", "balanced", "warm", "bowl", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: ["fish"],
        description: "A warm balanced bowl with salmon, rice, and vegetables.",
    },
    {
        id: "grilled-chicken-plate-rice-greens",
        title: "Grilled Chicken Plate with Rice and Greens",
        tags: ["balanced", "high-protein", "rice-based", "simple", "plate", "warm"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: [],
        description: "A simple balanced meal with lean protein, greens, and rice.",
    },
    {
        id: "tofu-vegetable-rice-bowl",
        title: "Tofu and Vegetable Rice Bowl",
        tags: ["balanced", "plant-protein", "rice-based", "warm", "bowl", "vegetable-forward"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: [],
        description: "A practical bowl with tofu, vegetables, and rice for a lighter balance.",
    },
    {
        id: "miso-fish-set-veg",
        title: "Miso Fish Set with Vegetables",
        tags: ["japanese-inspired", "balanced", "warm", "set-meal"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: ["fish"],
        description: "A warm set-style meal with fish, vegetables, and steady balance.",
    },
    {
        id: "shrimp-quinoa-bowl",
        title: "Shrimp Quinoa Bowl",
        tags: ["balanced", "high-protein", "bowl", "light"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: ["shellfish"],
        description: "A lighter bowl with shrimp, quinoa, and vegetables.",
    },
    {
        id: "chicken-broccoli-rice-bowl",
        title: "Chicken Broccoli Rice Bowl",
        tags: ["balanced", "high-protein", "rice-based", "everyday", "bowl", "warm", "takeout"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: [],
        description: "A familiar everyday meal that brings protein, vegetables, and comfort.",
    },
    {
        id: "tofu-vegetable-soup-rice",
        title: "Tofu Vegetable Soup with Rice",
        tags: ["soupy", "light", "gentle", "warm"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "light",
        avoidTags: [],
        description: "A gentle warm meal that feels lighter while still balanced.",
    },
    {
        id: "chicken-noodle-soup-greens",
        title: "Chicken Noodle Soup with Greens",
        tags: ["soupy", "comfort", "warm", "light"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked", "takeout"],
        mealType: "light",
        avoidTags: [],
        description: "A comforting soup choice with lean protein and a lighter feel.",
    },
    {
        id: "steamed-fish-rice-bokchoy",
        title: "Steamed Fish with Rice and Bok Choy",
        tags: ["light", "chinese-style", "warm", "steamed", "plate", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "low",
        worksFor: ["home-cooked"],
        mealType: "light",
        avoidTags: ["fish"],
        description: "A clean and gentle plate with steamed fish, greens, and rice.",
    },
    {
        id: "egg-tomato-rice",
        title: "Egg and Tomato over Rice",
        tags: ["chinese-style", "simple", "warm", "comfort", "rice-based", "bowl", "quick"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "light",
        avoidTags: [],
        description: "A simple home-style comfort meal that is easy and familiar.",
    },
    {
        id: "congee-egg-side-veg",
        title: "Congee with Egg and Side Vegetables",
        tags: ["gentle", "soupy", "comfort", "chinese-style"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "light",
        avoidTags: [],
        description: "A gentle meal for days when you want something soft and easy.",
    },
    {
        id: "miso-tofu-soup-rice",
        title: "Miso Tofu Soup with Rice",
        tags: ["japanese-inspired", "soupy", "light", "warm"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked", "takeout"],
        mealType: "light",
        avoidTags: [],
        description: "A warm light meal that feels comforting without being too heavy.",
    },
    {
        id: "chicken-wrap-salad",
        title: "Chicken Wrap with Salad",
        tags: ["convenient", "american-light", "portable", "quick"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "convenient",
        avoidTags: [],
        description: "A quick practical option with protein and vegetables.",
    },
    {
        id: "poke-bowl",
        title: "Poke Bowl",
        tags: ["convenient", "bowl", "takeout", "balanced"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "convenient",
        avoidTags: ["fish"],
        description: "A fast bowl-style option that usually feels balanced and fresh.",
    },
    {
        id: "turkey-sandwich-side-salad",
        title: "Turkey Sandwich with Side Salad",
        tags: ["american-light", "convenient", "portable", "quick"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A very practical meal when you want something easy and reasonably balanced.",
    },
    {
        id: "rotisserie-chicken-microwave-veg",
        title: "Rotisserie Chicken with Microwave Vegetables",
        tags: ["convenient", "high-protein", "quick", "everyday", "grocery", "plate"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "low",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A low-effort meal that still adds protein and some vegetables.",
    },
    {
        id: "soba-salad-egg",
        title: "Soba Salad with Egg",
        tags: ["japanese-inspired", "convenient", "light", "cold-meal", "noodle-based", "portable"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A light and practical choice when you want something easy but not too heavy.",
    },
    {
        id: "ready-made-soup-dumplings-veg",
        title: "Ready-Made Soup Dumplings with Vegetables",
        tags: ["convenient", "warm", "quick", "comfort", "set-meal", "grocery"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A fast comfort option that works better when paired with vegetables.",
    },
    {
        id: "beef-bibimbap-extra-veg",
        title: "Beef Bibimbap with Extra Vegetables",
        tags: ["korean-inspired", "rice-based", "flavorful", "balanced", "bowl", "vegetable-forward", "warm", "takeout"],
        proteinLevel: "high",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: ["beef"],
        description: "A flavorful bowl that adds protein and lots of vegetables.",
    },
    {
        id: "teriyaki-salmon-bowl",
        title: "Teriyaki Salmon Bowl",
        tags: ["japanese-inspired", "rice-based", "savory", "warm", "bowl"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: ["fish"],
        description: "A savory bowl for users who like warm rice-based meals with fish.",
    },
    {
        id: "taiwanese-bento-light",
        title: "Taiwanese Bento Light Version",
        tags: ["taiwanese-style", "set-meal", "warm", "comfort"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "preference",
        avoidTags: [],
        description: "A lighter bento-style option with familiar flavors and better balance.",
    },
    {
        id: "udon-soup-lean-protein",
        title: "Udon Soup with Lean Protein",
        tags: ["japanese-inspired", "soupy", "comfort", "warm"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: [],
        description: "A warm noodle option that feels comforting and not overly heavy.",
    },
    {
        id: "burrito-bowl-beans-veg",
        title: "Burrito Bowl with Beans and Vegetables",
        tags: ["mexican-inspired", "bowl", "hearty", "takeout", "warm", "convenient"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "preference",
        avoidTags: [],
        description: "A filling bowl with beans, vegetables, and flexible toppings.",
    },
    {
        id: "chicken-caesar-wrap-light",
        title: "Chicken Caesar Wrap Light Version",
        tags: ["american-light", "wrap", "convenient", "savory"],
        proteinLevel: "high",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "preference",
        avoidTags: ["dairy"],
        description: "A familiar convenient wrap that works for a quick protein-focused meal.",
    },
    {
        id: "kimchi-tofu-rice-bowl",
        title: "Kimchi Tofu Rice Bowl",
        tags: ["korean-inspired", "rice-based", "plant-protein", "warm", "bowl"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "preference",
        avoidTags: ["spicy"],
        description: "A bold warm bowl with tofu and flavor for users who enjoy stronger tastes.",
    },
    {
        id: "tofu-egg-protein-bowl",
        title: "Tofu and Egg Protein Bowl",
        tags: ["high-protein", "rice-based", "simple", "warm", "bowl"],
        proteinLevel: "high",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: [],
        description: "A simple protein-forward bowl when earlier meals were low in protein.",
    },
    {
        id: "bean-veggie-rice-bowl",
        title: "Bean and Vegetable Rice Bowl",
        tags: ["plant-protein", "fiber-support", "rice-based", "balanced", "bowl", "vegetable-forward", "warm"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "recovery",
        avoidTags: [],
        description: "A useful option for adding fiber variety, vegetables, and steady energy.",
    },
    {
        id: "grilled-chicken-sweet-potato-plate",
        title: "Grilled Chicken and Sweet Potato Plate",
        tags: ["high-protein", "simple", "balanced", "home-style", "plate", "warm"],
        proteinLevel: "high",
        vegetableLevel: "low",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: [],
        description: "A straightforward plate that helps add protein without feeling too heavy.",
    },
    {
        id: "salmon-edamame-bowl",
        title: "Salmon and Edamame Bowl",
        tags: ["high-protein", "japanese-inspired", "bowl", "balanced", "warm", "takeout"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "recovery",
        avoidTags: ["fish"],
        description: "A protein-supporting bowl with a lighter profile and balanced structure.",
    },
    {
        id: "vegetable-omelet-toast-fruit",
        title: "Vegetable Omelet with Toast and Fruit",
        tags: ["breakfast-for-dinner", "simple", "balanced", "quick", "plate", "light"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: [],
        description: "A quick balanced option that feels flexible and easy for any time of day.",
    },
    {
        id: "lean-beef-vegetable-noodle-soup",
        title: "Lean Beef Vegetable Noodle Soup",
        tags: ["soupy", "comfort", "warm", "hearty"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "recovery",
        avoidTags: ["beef"],
        description: "A warm soup option with protein and vegetables when you want something satisfying.",
    },
    {
        id: "rotisserie-chicken-rice-salad",
        title: "Rotisserie Chicken with Rice and Salad",
        tags: ["american-light", "balanced", "high-protein", "everyday", "grocery", "plate"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A realistic low-effort dinner using grocery staples that still feels complete.",
    },
    {
        id: "trader-joes-soup-salad",
        title: "Soup and Salad Combo",
        tags: ["light", "soupy", "convenient", "american-light", "grocery"],
        proteinLevel: "low",
        vegetableLevel: "high",
        carbLevel: "low",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked", "takeout"],
        mealType: "convenient",
        avoidTags: [],
        description: "A simple soup-and-salad pairing that works well when you want something light and easy.",
    },
    {
        id: "turkey-chili-rice-bowl",
        title: "Turkey Chili Rice Bowl",
        tags: ["warm", "high-protein", "bowl", "comfort"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "balanced",
        avoidTags: [],
        description: "A hearty but still practical bowl with turkey chili, rice, and a warmer feel.",
    },
    {
        id: "pho-lean-beef-herbs",
        title: "Pho with Lean Beef and Herbs",
        tags: ["soupy", "takeout", "warm", "noodle-based", "comfort"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "preference",
        avoidTags: ["beef"],
        description: "A light-feeling noodle soup that is easy to order and still satisfying.",
    },
    {
        id: "mediterranean-chicken-plate",
        title: "Mediterranean Chicken Plate",
        tags: ["balanced", "high-protein", "takeout", "plate", "mediterranean", "vegetable-forward", "warm"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "convenient",
        avoidTags: [],
        description: "A practical takeout plate with chicken, rice, and vegetables that usually balances well.",
    },
    {
        id: "falafel-salad-rice",
        title: "Falafel Salad with Rice",
        tags: ["plant-protein", "balanced", "takeout", "bowl", "mediterranean", "vegetable-forward", "light", "convenient"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "preference",
        avoidTags: [],
        description: "A plant-forward bowl with vegetables and enough substance to feel like a full meal.",
    },
    {
        id: "costco-salmon-sweet-potato-veg",
        title: "Baked Salmon with Sweet Potato and Vegetables",
        tags: ["balanced", "high-protein", "home-style", "warm", "grocery", "plate", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: ["fish"],
        description: "A straightforward plate that feels balanced and easy to repeat on a normal weeknight.",
    },
    {
        id: "mapo-tofu-light-rice",
        title: "Mapo Tofu Light Version with Rice",
        tags: ["chinese-style", "warm", "rice-based", "comfort", "bowl"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "preference",
        avoidTags: ["spicy"],
        description: "A lighter take on a familiar comfort dish that still works for everyday dinner.",
    },
    {
        id: "beef-tomato-rice-bowl",
        title: "Beef and Tomato Rice Bowl",
        tags: ["chinese-style", "rice-based", "warm", "comfort", "bowl"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "preference",
        avoidTags: ["beef"],
        description: "A familiar home-style bowl with a practical mix of protein, tomato, and rice.",
    },
    {
        id: "taiwanese-minced-pork-rice-light",
        title: "Taiwanese Minced Pork Rice Light Version",
        tags: ["taiwanese-style", "rice-based", "comfort", "warm", "bowl"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "preference",
        avoidTags: ["pork"],
        description: "A lighter version of a familiar rice bowl that still feels satisfying and recognizable.",
    },
    {
        id: "japanese-curry-light-set",
        title: "Japanese Curry Light Set",
        tags: ["japanese-inspired", "set-meal", "warm", "comfort"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "preference",
        avoidTags: [],
        description: "A gentler curry-style set that keeps the comfort but avoids feeling too heavy.",
    },
    {
        id: "tuna-mayo-onigiri-side-soup",
        title: "Onigiri with Side Soup and Fruit",
        tags: ["japanese-inspired", "convenient", "light", "portable", "grocery"],
        proteinLevel: "low",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked", "takeout"],
        mealType: "convenient",
        avoidTags: ["fish"],
        description: "A very practical light meal when you want something quick and easy to put together.",
    },
    {
        id: "avocado-egg-toast-soup",
        title: "Avocado Toast with Egg and Soup",
        tags: ["breakfast-for-dinner", "simple", "light", "quick"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: ["egg"],
        description: "A flexible quick meal that works well when dinner needs to stay simple.",
    },
    {
        id: "greek-yogurt-granola-fruit-bowl",
        title: "Greek Yogurt Granola Fruit Bowl",
        tags: ["light", "quick", "breakfast-for-dinner", "cold-meal"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: ["dairy"],
        description: "A low-friction option for nights when you want something very easy and not heavy.",
    },
    {
        id: "cottage-cheese-fruit-toast-plate",
        title: "Cottage Cheese, Fruit, and Toast Plate",
        tags: ["light", "quick", "simple", "breakfast-for-dinner"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: ["dairy"],
        description: "A very easy plate that covers protein, carbs, and fruit without much effort.",
    },
    {
        id: "edamame-noodle-salad",
        title: "Edamame Noodle Salad",
        tags: ["plant-protein", "noodle-based", "light", "cold-meal"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: [],
        description: "A lighter noodle option with plant protein that still feels like a real meal.",
    },
    {
        id: "chicken-sub-soup-combo",
        title: "Chicken Sub with Side Soup",
        tags: ["american-light", "convenient", "takeout", "comfort", "portable"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "convenient",
        avoidTags: [],
        description: "A realistic quick combo when convenience matters more than cooking from scratch.",
    },
    {
        id: "shrimp-fried-rice-light-veg",
        title: "Shrimp Fried Rice with Extra Vegetables",
        tags: ["chinese-style", "rice-based", "takeout", "warm", "vegetable-forward"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "high",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: ["shellfish"],
        description: "A familiar takeout-style meal that works better when paired with extra vegetables.",
    },
    {
        id: "tofu-kale-quinoa-bowl",
        title: "Tofu Kale Quinoa Bowl",
        tags: ["plant-protein", "light", "balanced", "bowl"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "recovery",
        avoidTags: [],
        description: "A lighter grain bowl that brings vegetables and plant protein without much heaviness.",
    },
    {
        id: "egg-drop-soup-dumpling-side-veg",
        title: "Egg Drop Soup with Dumplings and Greens",
        tags: ["soupy", "warm", "comfort", "chinese-style"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: ["egg"],
        description: "A warm comfort combination that feels more complete with soup and greens together.",
    },
    {
        id: "gyro-bowl-rice-salad",
        title: "Gyro Bowl with Rice and Salad",
        tags: ["takeout", "bowl", "savory", "balanced", "mediterranean"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "preference",
        avoidTags: [],
        description: "A practical takeout bowl with enough structure to feel balanced and satisfying.",
    },
    {
        id: "turkey-avocado-sandwich-soup",
        title: "Turkey Avocado Sandwich with Soup",
        tags: ["american-light", "portable", "comfort", "quick", "sandwich", "convenient"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A practical sandwich-and-soup combo that feels easy, familiar, and reasonably balanced.",
    },
    {
        id: "chicken-fajita-bowl",
        title: "Chicken Fajita Bowl",
        tags: ["mexican-inspired", "bowl", "takeout", "vegetable-forward", "warm", "convenient"],
        proteinLevel: "high",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: [],
        description: "A colorful bowl with chicken and peppers that adds vegetables without losing practicality.",
    },
    {
        id: "soy-garlic-chicken-rice-cabbage",
        title: "Soy Garlic Chicken with Rice and Cabbage",
        tags: ["korean-inspired", "rice-based", "warm", "comfort", "plate", "takeout"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "preference",
        avoidTags: [],
        description: "A savory rice plate that feels familiar and satisfying without going too heavy.",
    },
    {
        id: "tofu-mushroom-udon-soup",
        title: "Tofu Mushroom Udon Soup",
        tags: ["japanese-inspired", "soupy", "warm", "plant-protein"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: [],
        description: "A warm noodle soup that gives you comfort, tofu protein, and a lighter overall feel.",
    },
    {
        id: "canned-soup-toast-egg",
        title: "Canned Soup with Toast and Egg",
        tags: ["quick", "grocery", "comfort", "breakfast-for-dinner", "warm", "soupy"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: ["egg"],
        description: "A very low-effort meal that still feels warm and complete on a busy night.",
    },
    {
        id: "baked-salmon-bagged-salad-potato",
        title: "Baked Salmon with Bagged Salad and Potato",
        tags: ["balanced", "home-style", "warm", "grocery", "plate", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "balanced",
        avoidTags: ["fish"],
        description: "A realistic grocery-based dinner that brings protein and vegetables without much friction.",
    },
    {
        id: "hummus-chicken-wrap-fruit",
        title: "Hummus Chicken Wrap with Fruit",
        tags: ["mediterranean", "wrap", "portable", "light"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A portable wrap option that feels light, practical, and easy to act on.",
    },
    {
        id: "veggie-black-bean-quesadilla-salad",
        title: "Veggie Black Bean Quesadilla with Salad",
        tags: ["mexican-inspired", "plant-protein", "comfort", "takeout", "vegetable-forward"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: ["dairy"],
        description: "A flexible comfort-style meal with beans and vegetables that still feels approachable.",
    },
    {
        id: "scallion-egg-tofu-rice-bowl",
        title: "Scallion Egg Tofu Rice Bowl",
        tags: ["chinese-style", "rice-based", "simple", "plant-protein", "bowl", "warm"],
        proteinLevel: "high",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: ["egg"],
        description: "A simple bowl that is easy to make when you want more protein without extra heaviness.",
    },
    {
        id: "soba-tofu-bento",
        title: "Soba and Tofu Bento",
        tags: ["japanese-inspired", "set-meal", "portable", "light"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A tidy set-style meal that travels well and keeps the overall feel light.",
    },
    {
        id: "chicken-cabbage-dumpling-soup",
        title: "Chicken and Cabbage Dumpling Soup",
        tags: ["soupy", "warm", "comfort", "chinese-style", "gentle"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "balanced",
        avoidTags: [],
        description: "A warm soup-based meal that feels comforting while still keeping some structure and balance.",
    },
    {
        id: "ginger-chicken-rice-soup",
        title: "Ginger Chicken Rice Soup",
        tags: ["soupy", "warm", "comfort", "gentle", "chinese-style"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "light",
        avoidTags: [],
        description: "A gentle warm soup with chicken and rice that works well when you want something soothing and steady.",
    },
    {
        id: "tofu-mushroom-congee",
        title: "Tofu Mushroom Congee",
        tags: ["soupy", "warm", "gentle", "comfort", "plant-protein", "chinese-style"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "light",
        avoidTags: [],
        description: "A soft warm bowl that feels easy on the stomach while still giving you protein and comfort.",
    },
    {
        id: "salmon-miso-porridge",
        title: "Salmon Miso Porridge",
        tags: ["japanese-inspired", "warm", "soupy", "comfort", "gentle"],
        proteinLevel: "high",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: ["fish"],
        description: "A warm porridge-style meal with salmon that feels soft, steady, and comforting.",
    },
    {
        id: "soft-noodle-soup-egg-greens",
        title: "Soft Noodle Soup with Egg and Greens",
        tags: ["soupy", "warm", "comfort", "gentle", "noodle-based"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "light",
        avoidTags: ["egg"],
        description: "A soft noodle soup that feels gentle and warming without turning into a heavy meal.",
    },
    {
        id: "steamed-fish-vegetable-plate",
        title: "Steamed Fish and Vegetable Plate",
        tags: ["light", "warm", "steamed", "balanced", "chinese-style", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "high",
        carbLevel: "low",
        heaviness: "light",
        convenience: "low",
        worksFor: ["home-cooked"],
        mealType: "light",
        avoidTags: ["fish"],
        description: "A lighter plate with fish and vegetables that works well when you want something clean and not too much.",
    },
    {
        id: "tofu-greens-soup-small-rice",
        title: "Tofu Greens Soup with Small Rice",
        tags: ["soupy", "light", "warm", "plant-protein", "vegetable-forward"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "light",
        avoidTags: [],
        description: "A warm soup-and-rice combination that keeps the meal light while still feeling complete.",
    },
    {
        id: "chicken-salad-grain-bowl-light",
        title: "Chicken Salad Grain Bowl Light Version",
        tags: ["light", "balanced", "bowl", "american-light", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "high",
        carbLevel: "low",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "balanced",
        avoidTags: [],
        description: "A lighter grain bowl with chicken and plenty of vegetables when you want something fresh but still real.",
    },
    {
        id: "miso-tofu-spinach-bowl",
        title: "Miso Tofu and Spinach Bowl",
        tags: ["japanese-inspired", "plant-protein", "warm", "light", "bowl"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "recovery",
        avoidTags: [],
        description: "A warm light bowl that gives you tofu, greens, and a calmer overall feel.",
    },
    {
        id: "rotisserie-chicken-microwave-veg-rice",
        title: "Rotisserie Chicken with Microwave Vegetables and Rice",
        tags: ["quick", "grocery", "high-protein", "warm", "convenient", "plate"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A realistic grocery shortcut meal that still covers protein, vegetables, and a familiar starch.",
    },
    {
        id: "frozen-dumplings-bok-choy",
        title: "Frozen Dumplings with Bok Choy",
        tags: ["quick", "warm", "comfort", "grocery", "chinese-style", "set-meal"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A very doable comfort meal that feels better balanced when paired with greens.",
    },
    {
        id: "greek-yogurt-fruit-granola-bowl",
        title: "Greek Yogurt Fruit Granola Bowl",
        tags: ["quick", "breakfast-for-dinner", "light", "grocery", "portable"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: ["dairy"],
        description: "A very easy bowl that works when you want something low-effort and not too heavy.",
    },
    {
        id: "beef-tomato-noodle-soup",
        title: "Beef Tomato Noodle Soup",
        tags: ["soupy", "warm", "comfort", "chinese-style", "noodle-based"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "preference",
        avoidTags: ["beef"],
        description: "A familiar warm noodle soup that feels comforting and satisfying in a very everyday way.",
    },
    {
        id: "egg-tofu-congee",
        title: "Egg Tofu Congee",
        tags: ["soupy", "warm", "gentle", "comfort", "chinese-style", "plant-protein"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked"],
        mealType: "light",
        avoidTags: ["egg"],
        description: "A soft, simple congee that feels gentle and easy to settle into on lower-energy days.",
    },
    {
        id: "chicken-ginger-noodle-soup",
        title: "Chicken Ginger Noodle Soup",
        tags: ["soupy", "warm", "comfort", "gentle", "noodle-based"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["home-cooked", "takeout"],
        mealType: "light",
        avoidTags: [],
        description: "A warm ginger-forward soup that feels soothing while still giving you a proper meal.",
    },
    {
        id: "warm-soba-broth-set",
        title: "Warm Soba Broth Set",
        tags: ["japanese-inspired", "soupy", "warm", "set-meal", "light"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "convenient",
        avoidTags: [],
        description: "A tidy warm set that feels comforting and light enough for days when you want less friction.",
    },
    {
        id: "soy-milk-oatmeal-egg-fruit",
        title: "Soy Milk Oatmeal with Egg and Fruit",
        tags: ["breakfast-for-dinner", "warm", "gentle", "quick", "light", "grocery", "plate"],
        proteinLevel: "medium",
        vegetableLevel: "low",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["home-cooked"],
        mealType: "convenient",
        avoidTags: ["egg"],
        description: "A very easy warm meal that works well when you want something soft, familiar, and uncomplicated.",
    },
    {
        id: "taiwanese-three-cup-chicken-light-set",
        title: "Taiwanese Three Cup Chicken Light Set",
        tags: ["taiwanese-style", "set-meal", "warm", "comfort", "takeout"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: [],
        description: "A lighter set-style take on a familiar Taiwanese favorite with enough structure to feel balanced.",
    },
    {
        id: "taiwanese-shredded-chicken-rice-veg",
        title: "Taiwanese Shredded Chicken Rice with Vegetables",
        tags: ["taiwanese-style", "rice-based", "warm", "everyday", "bowl", "convenient"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: [],
        description: "A practical rice meal with familiar Taiwanese flavors that still keeps the overall feel steady.",
    },
    {
        id: "korean-soft-tofu-soup-rice",
        title: "Korean Soft Tofu Soup with Rice",
        tags: ["korean-inspired", "soupy", "warm", "comfort", "gentle"],
        proteinLevel: "medium",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "light",
        avoidTags: ["spicy"],
        description: "A warm tofu soup meal that feels comforting, protein-supportive, and easier on heavier days.",
    },
    {
        id: "dak-galbi-light-bowl",
        title: "Dak-galbi Light Bowl",
        tags: ["korean-inspired", "rice-based", "warm", "bowl", "takeout"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: ["spicy"],
        description: "A Korean-style chicken bowl that stays flavorful without leaning too far into heaviness.",
    },
    {
        id: "chicken-taco-rice-bowl",
        title: "Chicken Taco Rice Bowl",
        tags: ["mexican-inspired", "bowl", "takeout", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "medium",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout", "home-cooked"],
        mealType: "preference",
        avoidTags: [],
        description: "A very approachable Mexican-inspired bowl with chicken, rice, and enough vegetables to feel complete.",
    },
    {
        id: "shrimp-fajita-plate",
        title: "Shrimp Fajita Plate",
        tags: ["mexican-inspired", "warm", "plate", "vegetable-forward"],
        proteinLevel: "high",
        vegetableLevel: "high",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "balanced",
        avoidTags: ["shellfish"],
        description: "A lighter fajita-style plate that brings plenty of vegetables and steady protein.",
    },
    {
        id: "mediterranean-salmon-plate",
        title: "Mediterranean Salmon Plate",
        tags: ["mediterranean", "plate", "balanced", "vegetable-forward", "warm"],
        proteinLevel: "high",
        vegetableLevel: "high",
        carbLevel: "low",
        heaviness: "light",
        convenience: "medium",
        worksFor: ["takeout", "home-cooked"],
        mealType: "balanced",
        avoidTags: ["fish"],
        description: "A Mediterranean-style plate with salmon, vegetables, and a lighter overall profile.",
    },
    {
        id: "falafel-rice-salad-bowl",
        title: "Falafel Rice and Salad Bowl",
        tags: ["mediterranean", "bowl", "plant-protein", "vegetable-forward"],
        proteinLevel: "medium",
        vegetableLevel: "high",
        carbLevel: "medium",
        heaviness: "medium",
        convenience: "high",
        worksFor: ["takeout"],
        mealType: "preference",
        avoidTags: [],
        description: "A Mediterranean bowl that adds vegetables and plant protein while staying easy to pick up.",
    },
];
export const seededState = createSeededState();
